PM:
  host: iadvize.atlassian.net
  project: SAN
  create_issue: true
  adapter: jira
SCM:
  workflow: none
  adapter: git
  remote: origin
VCS:
  create_issue: false
  pr_create: true
  adapter: github
